Repository signatureai/signature-nodes, pull requests merged in 2025-02, with the labels that each got.

#70 ML-505: Mark outputs as disabled
  nodes/neurochain/agents/florence2/florence2.py
  nodes/web/florence2.js
Labels: bug

#65 ML-365: Merge signature-dojo nodes
  nodes/categories.py
  nodes/neurochain/dojo/create_training_run.py
  nodes/neurochain/dojo/start_training_run.py
  nodes/neurochain/storage/s3/download_from_s3.py
  nodes/neurochain/utils.py
  nodes/neurochain/vectorstores/query_vectorstore.py
  nodes/neurochain/vectorstores/upload_to_vectorstore.py
Labels: minor

#69 feat: create batch builder node
  nodes/utils.py
  nodes/web/dynamic_input_amount.js
Labels: minor

#74 feat: use description as fallback for documentation
  scripts/generate_docs.py
Labels: minor

#73 Feat/ml 521 implement multi variable support in simple math node
  nodes/js/image_selector.js
  nodes/numbers.py
  nodes/utils.py
  nodes/web/dynamic_input_amount.js
Labels: minor

#83 Feat/ml 565 separate the styling from functional js for sig platform io nodes
  nodes/platform_io.py
  nodes/web/platform_io_functional.js
  nodes/web/platform_io_style.js
Labels: minor

#82 feat: implement check lazy status logic
  nodes/logic.py
Labels: minor

#84 fix: separate multiple URL with space instead of comma
  nodes/platform_io.py
Labels: minor

#90 Refactor/remove base64 support
  nodes/file.py
  nodes/platform_io.py
Labels: minor

#98 Bug/ml 614 platform io js
  nodes/web/platform_io_functional.js
  nodes/web/platform_io_style.js
Labels: bug, minor

#99 Fix/ml 615 remove prompt option of sig input text node
  nodes/platform_io.py
  nodes/web/loops.js
  nodes/web/platform_io_functional.js
  nodes/web/platform_io_style.js
  nodes/web/visual.js
Labels: bug, minor
